import localFont from "next/font/local";
import "../globals.css";
import Navbar from "@/components/Navbar";
import SideBar from "@/components/SideBar";
import BottomBar from "@/components/BottomBar";
import { UserProvider } from "@/context/UserContext";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";
import Head from "next/head";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //   const { user } = await validateRequest();
  //   if (!user) {
  //     console.log("redirect to sign in page");
  //     return redirect("/auth/sign-in");
  //   }

  return (
    <html lang="en">
      <Head>
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://leetreviews.com/" />
        <meta
          property="og:title"
          content="Leet Reviews - Honest Workplace Feedback"
        />
        <meta
          property="og:description"
          content="Discover and share honest workplace feedback with Leet Reviews."
        />
        <meta property="og:image" content="https://leetreviews.com/_.jpeg" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url('/bg.svg')] bg-cover bg-center bg-no-repeat text-neutral w-full h-screen flex flex-col`}
      >
        <Suspense>
          <UserProvider>
            <Navbar />
            <div
              className={`flex overflow-y-auto overflow-x-hidden light-scroll`}
            >
              <SideBar />
              <BottomBar />
              <div className="h-max w-full mt-[100px] max-md:mt-[150px]">
                {children}
              </div>
            </div>
          </UserProvider>
          <Toaster
            toastOptions={{
              className: "",
              style: {
                color: "#FFF5E0",
                backgroundColor: "#141E46",
              },
            }}
          />
        </Suspense>
      </body>
    </html>
  );
}
